"""Stage 5 — Export textured mesh as OBJ + MTL + PNG.

Writes:
    {output_dir}/{name}.obj
    {output_dir}/{name}.mtl
    {output_dir}/{name}_texture.png
    {output_dir}/{name}.glb          (optional, if trimesh can do it)
"""

from __future__ import annotations

from pathlib import Path

import cv2
import numpy as np
import trimesh


def export_obj(
    mesh_uv: trimesh.Trimesh,
    uvs: np.ndarray,
    obj_pose: np.ndarray,
    atlas_bgr: np.ndarray,
    name: str,
    output_dir: str | Path,
    also_glb: bool = True,
) -> dict[str, Path]:
    """Write the textured OBJ mesh and accompanying files.

    Args:
        mesh_uv: Trimesh with remapped vertices and UV stored in metadata["uvs"].
        uvs: (V_uv, 2) UV in [0, 1].
        obj_pose: (4, 4) object-to-world transform to bake into vertex positions.
        atlas_bgr: (H, W, 3) uint8 BGR texture atlas.
        name: base name (no extension) for output files.
        output_dir: directory to write files into.
        also_glb: whether to also write a .glb file.

    Returns:
        dict mapping 'obj', 'mtl', 'texture' (and 'glb') to their Paths.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    obj_path = out / f"{name}.obj"
    mtl_path = out / f"{name}.mtl"
    tex_path = out / f"{name}_texture.png"
    glb_path = out / f"{name}.glb"

    # Bake the object pose into vertex positions
    verts_local = np.asarray(mesh_uv.vertices, dtype=np.float64)
    N = len(verts_local)
    V_h = np.ones((N, 4))
    V_h[:, :3] = verts_local
    verts_world = (obj_pose @ V_h.T).T[:, :3]

    faces = np.asarray(mesh_uv.faces, dtype=np.int32)

    # UV coordinates (flip V because OBJ uses bottom-left origin)
    uv_obj = uvs.copy()
    uv_obj[:, 1] = 1.0 - uv_obj[:, 1]

    # Write MTL
    with open(mtl_path, "w") as f:
        f.write(f"newmtl {name}\n")
        f.write(f"map_Kd {tex_path.name}\n")
        f.write("Ka 1.0 1.0 1.0\n")
        f.write("Kd 1.0 1.0 1.0\n")
        f.write("Ks 0.0 0.0 0.0\n")
        f.write("d 1.0\n")

    # Write OBJ
    with open(obj_path, "w") as f:
        f.write(f"# Textured mesh — generated by texture_pipeline\n")
        f.write(f"mtllib {mtl_path.name}\n")
        f.write(f"usemtl {name}\n\n")

        # Vertices
        for v in verts_world:
            f.write(f"v {v[0]:.8f} {v[1]:.8f} {v[2]:.8f}\n")

        # UV coordinates
        for uv in uv_obj:
            f.write(f"vt {uv[0]:.8f} {uv[1]:.8f}\n")

        # Faces (1-indexed, v/vt format)
        # Assuming 1-to-1 vertex ↔ UV (true when xatlas remaps the mesh)
        for face in faces:
            i, j, k = face + 1  # OBJ is 1-indexed
            f.write(f"f {i}/{i} {j}/{j} {k}/{k}\n")

    # Write texture PNG (convert BGR → RGB for PIL/PNG)
    atlas_rgb = cv2.cvtColor(atlas_bgr, cv2.COLOR_BGR2RGB)
    from PIL import Image
    Image.fromarray(atlas_rgb).save(str(tex_path))

    paths = {"obj": obj_path, "mtl": mtl_path, "texture": tex_path}

    # Optionally write GLB
    if also_glb:
        try:
            _write_glb(mesh_uv, uvs, obj_pose, atlas_bgr, glb_path)
            paths["glb"] = glb_path
        except Exception as e:
            print(f"  [export] GLB export skipped: {e}")

    print(f"  [export] Written: {obj_path.name}, {mtl_path.name}, {tex_path.name}")
    return paths


def _write_glb(
    mesh_uv: trimesh.Trimesh,
    uvs: np.ndarray,
    obj_pose: np.ndarray,
    atlas_bgr: np.ndarray,
    glb_path: Path,
) -> None:
    """Export as GLB using trimesh's built-in GLTF writer."""
    # Build a trimesh with UV and texture material
    verts_local = np.asarray(mesh_uv.vertices, dtype=np.float64)
    N = len(verts_local)
    V_h = np.ones((N, 4))
    V_h[:, :3] = verts_local
    verts_world = (obj_pose @ V_h.T).T[:, :3]

    faces = np.asarray(mesh_uv.faces, dtype=np.int32)

    # Convert atlas to PIL image
    from PIL import Image
    atlas_rgb = cv2.cvtColor(atlas_bgr, cv2.COLOR_BGR2RGB)
    pil_img = Image.fromarray(atlas_rgb)

    material = trimesh.visual.texture.SimpleMaterial(image=pil_img)
    uv_flipped = uvs.copy()
    uv_flipped[:, 1] = 1.0 - uv_flipped[:, 1]

    visual = trimesh.visual.TextureVisuals(uv=uv_flipped, material=material)
    export_mesh = trimesh.Trimesh(vertices=verts_world, faces=faces, visual=visual, process=False)
    export_mesh.export(str(glb_path))
    print(f"  [export] Written: {glb_path.name}")
